name: CI docker

on:
    push: 
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # github tự động clone responsibility của bạn về máy ảo 
            - uses: actions/checkout@v4
            
            #
            - name: đăng nhập dockerhub 
              run: docker login -u duonggquocc -p ${{secrets.PASS_DOCKER}}  

            - name: Build Image Docker
              run: docker build -t duonggquocc/img-cyber_community:latest .

            - name: Push Image lên docker hub 
              run: docker push duonggquocc/img-cyber_community:latest